[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodejs-22_x", "php82", "php82Extensions.exif"]

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"