[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodejs-22_x", "php82", "php82Extensions.exif"]

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"